apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-aws
  labels:
    app: {{ template "fullname" . }}
data:
  queue: {{ .Values.sqs.queue }}
  access_key_id: {{ .Values.aws.access_key_id }}
