apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-app
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        app: {{ template "fullname" . }}
        release: {{ .Release.Name }}
        component: flyway
    spec:
      containers:
      - name: flyway-migration
        image: {{ .Values.flyway.image }}:{{ .Values.flyway.imageTag }}
        imagePullPolicy: {{ .Values.flyway.imagePullPolicy }}
        env:
        - name: FLYWAY_URL
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}-postgres
              key: url
        - name: FLYWAY_USER
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}-postgres
              key: user
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}-postgres
              key: password
      restartPolicy: Never
